server:
  compression:
     enabled: true
     mime-types: application/json,application/xml,text/html,text/xml,text/plain
  server-header: salesforce-connector

sf:
   soqlQueryPath: services/data/v44.0/query
   addContactPath: services/data/v44.0/sobjects/Contact
   opportunityContactLinkPath: services/data/v44.0/sobjects/OpportunityContactRole
   opportunityFieldsUpdatePath: services/data/v44.0/sobjects/Opportunity/

management:
  endpoints:
    web.base-path: /
